kind: pipeline
type: docker
name: Build and Publish Image

steps:
  - name: Get version
    image: alpine
    commands:
    - SEMVER_MAJOR="$$(cat VERSION | cut -d. -f1)"
    - SEMVER_MINOR="$$(cat VERSION | cut -d. -f2)"
    - SEMVER_PATCH="$$(cat VERSION | cut -d. -f3)"

    - DOCKER_REPO=jackbailey/ip

    - echo -n "latest,$SEMVER_MAJOR.$SEMVER_MINOR.$SEMVER_PATCH,$SEMVER_MAJOR.$SEMVER_MINOR,$SEMVER_MAJOR" > .tags
      
  - name: docker
    image: plugins/docker
    settings:
      username:
        from_secret: DOCKERHUB_USERNAME
      password:
          from_secret: DOCKERHUB_PASSWORD
      repo: jackbailey/ip
      dockerfile: Dockerfile