name: Docker Image CI

on:
    push:
        

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - name: Build Docker image
              uses: flownative/action-docker-build@master
              with:
                tag_ref: ${{ github.ref }}
                image_name: jackbailey/ip
                registry_password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
            - name: Publish release to docker.io
              uses: flownative/action-docker-publish-semver@master
              with:
                tag_ref: ${{ github.ref }}
                tag_latest: 'yes'
      
                source_image_name: jackbailey/test
      
                target_image_name: jackbailey/test
                target_registry_username: jackbailey
                target_registry_password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
                target_registry_endpoint: https://index.docker.io/v1/
